#!/bin/bash
[[ -f /usr/sbin/configsnap ]] && /usr/sbin/configsnap -d /root -t auter-configsnap-"$(date +%Y-%m-%d)" -p post-reboot &> /root/auter-configsnap-"$(date +%Y-%m-%d)"/configsnap/post-reboot.compare
